init stdlib
shihai1991/CPython-Internals pull request #1
Opened 2022-03-22 12:51 UTC by lijunchen

2022-03-23 02:13 UTC, CharlieZhao95 requested changes
Looking good! I suggested some changes, you could be able to just a click a button to accept them, if you agree with them.

2022-03-23 02:13 UTC, CharlieZhao95 commented on stdlib/python-and-c-module.md
> +除了时间模块，其他的有同一个 API 接口，但是有多个实现的模块还有线程模块、文件系统模块和网络模块。 因为不同操作系统的行为不同，CPython 只能尽可能地实现相同的行为，使用一致的、抽象的接口暴露操作系统的接口。
```suggestion
除了时间模块，使用同一个 API 接口但是有多组底层实现的模块还包括线程模块、文件系统模块和网络模块。 因为不同操作系统的行为不同，CPython 只能尽可能地实现相同的行为，使用一致的、抽象的接口暴露操作系统的接口。
```

2022-03-23 07:33 UTC, shihai1991 commented on stdlib/README.md
> +CPython的这些“自带电池”就像是五号电池，它对所有东西都很有用，比如 collections 模块和 sys 模块。但也有些不常用的模块，就像小型手表电池那样你不知道什么时候会派上用场。
它们对所有东西都很有用

2022-03-23 07:33 UTC, shihai1991 commented on stdlib/README.md
> +1. 用纯 Python 编写的
1. 用纯 Python 编写的功能模块
2. 用 C 编写并用Python进行封装的模块

2022-03-23 07:33 UTC, shihai1991 commented on stdlib/README.md
> +你将在本章中探索这两种类型。
这两种模块类型。

2022-03-23 07:33 UTC, shihai1991 commented on stdlib/python-module.md
> +## Python 模块
这个空不用多加吧

2022-03-23 10:32 UTC, lijunchen commented on stdlib/python-module.md
> +也有一些简单的模块是单个文件，比如 colorsys 模块，它只有几百行 Python 代码。大部分人之前可能都没听说过这个模块，colorsys 模块提供了在 `RGB` 和其他颜色系统之间的转换函数。
这句话我参考了 https://github.com/python/cpython/blob/3.10/Lib/colorsys.py 还是需要确定一下翻译原则

2022-03-25 02:44 UTC, CharlieZhao95 commented on stdlib/python-module.md
> +也有一些简单的模块是单个文件，比如 colorsys 模块，它只有几百行 Python 代码。大部分人之前可能都没听说过这个模块，colorsys 模块提供了在 `RGB` 和其他颜色系统之间的转换函数。
OK, 第一眼看到颜色系统会让人有一些困惑，是不是色彩系统描述更专业一些。

2022-03-25 15:13 UTC, lijunchen commented on stdlib/python-module.md
> +也有一些简单的模块是单个文件，比如 colorsys 模块，它只有几百行 Python 代码。大部分人之前可能都没听说过这个模块，colorsys 模块提供了在 `RGB` 和其他颜色系统之间的转换函数。
嗯，调研了一下，这个术语中英文都没有标准的说法，基本上就是{颜色，色彩，彩色}和{空间，模型，系统}的组合

2022-03-27 16:06 UTC, shihai1991 approved these changes
LGTM，还有一些小细节问题你在辛苦看看。

2022-03-27 16:06 UTC, shihai1991 commented on stdlib/python-and-c-module.md
> +在函数 `_PyTime_GetProcessTimeWithInfo()` 的源码中可以看到，不同操作系统上实现该函数的方式不同，这些不同的实现方式使用宏来控制，编译时会根据操作系统编译所需要的代码到模块中。Windows 系统将调用 `GetProcessTimes()`，而 Unix 系统将调用 `clock_gettime()`。
> 在函数 `_PyTime_GetProcessTimeWithInfo()`

这个我建议我们加个翻译规范，统一如你上文翻译的，都写成在**`xxxx`函数中**，你意见如何？

2022-03-27 16:06 UTC, shihai1991 commented on stdlib/python-and-c-module.md
> +除了时间模块，使用同一个 API 接口但是有多组底层实现的模块还包括线程模块、文件系统模块和网络模块。由于操作系统的行为不同，CPython 源码中通过使用一致的、抽象的接口，尽可能的向上层调用者暴露出相同的行为。
> 使用同一个 API 接口

这里我理解应该是对外提供同一个API接口

2022-03-27 16:21 UTC, lijunchen commented on stdlib/python-and-c-module.md
> +一些用 C 语言编写的模块的需要依赖操作系统提供的接口。并且 CPython 源代码需要编译到 macOS、Windows、Linux 和其他 *nix 操作系统，所以不得不考虑各种特殊情况。
英文没区别，不过我理解这里想表达的意思其实就是依赖于具体的操作系统接口，如果翻译成暴露OS的函数，感觉大部分人看不懂

2022-03-27 16:25 UTC, lijunchen commented on stdlib/python-and-c-module.md
> +在函数 `_PyTime_GetProcessTimeWithInfo()` 的源码中可以看到，不同操作系统上实现该函数的方式不同，这些不同的实现方式使用宏来控制，编译时会根据操作系统编译所需要的代码到模块中。Windows 系统将调用 `GetProcessTimes()`，而 Unix 系统将调用 `clock_gettime()`。
确实这种类似的模式统一规范一下比较好

2022-03-27 16:28 UTC, lijunchen commented on stdlib/python-and-c-module.md
> +3. 变量`file`被设置成`PyId_stdout`，也即系统的`stdout`
又检查了一遍，应该全加了

2022-03-28 01:26 UTC, shihai1991 commented on stdlib/python-and-c-module.md
> +一些用 C 语言编写的模块的需要依赖操作系统提供的接口。并且 CPython 源代码需要编译到 macOS、Windows、Linux 和其他 *nix 操作系统，所以不得不考虑各种特殊情况。
> 英文没区别，不过我理解这里想表达的意思其实就是依赖于具体的操作系统接口，如果翻译成暴露OS的函数，感觉大部分人看不懂

哦，你说的也对。好的，那这里就保持这个样子吧。

2022-03-28 01:49 UTC, merged