翻译Configuration and input剩余的两个小节
shihai1991/CPython-Internals pull request #21
Opened 2022-06-06 11:36 UTC by lvluling

gitbook预览链接：
https://lvluling1.gitbook.io/cpython-internals/configuration-and-input/configuration-state
https://lvluling1.gitbook.io/cpython-internals/configuration-and-input/building-a-module-from-input

2022-06-07 02:06 UTC, CharlieZhao95 requested changes
Review in Configuration state

2022-06-07 02:06 UTC, CharlieZhao95 commented on configuration-and-input/configuration-state.md
> +CPython 解释器有一组运行时标志，这些标志是用于切换 CPython 特定行为的高级功能。 在 Python 会话中，您可以使用名为 tuple 的 `sys.flags` 访问运行时标志，例如 verbose 模式和 quiet 模式。所有通过 `-X` 指定的标志都会在 `sys._xoptions` 字典中生效：
此处应该原文有一些错误
```suggestion
CPython 解释器有一组运行时标志，这些标志是用于切换 CPython 特定行为的高级功能。 在 Python 会话中，您可以使用名为 `sys.flags`  的 tuple 去访问运行时标志，例如 verbose 模式和 quiet 模式。所有通过 `-X` 指定的标志都会在 `sys._xoptions` 字典中生效：

```

2022-06-13 03:23 UTC, xiaochen7 commented on configuration-and-input/configuration-state.md
> +上述的两个数据结构都在 Include/cpython/initconfig.h 文件中定义。
> 运行时的配置存在于以下三个数据结构中

> 上述的两个数据结构都在

这里该是三个还是两个呀

2022-06-13 03:23 UTC, xiaochen7 commented on configuration-and-input/configuration-state.md
> +| configure_locale           | 将 `LC_CTYPE` 语言环境设置为用户首选语言环境。如果等于0，则将 `coerce_c_locale` 和 `coerce_c_locale_warn` 设置为0 |
```suggestion
| configure_locale           | 将 `LC_CTYPE` 语言环境设置为用户首选语言环境。如果等于 0，则将 `coerce_c_locale` 和 `coerce_c_locale_warn` 设置为 0 |

```

2022-06-13 03:23 UTC, xiaochen7 commented on configuration-and-input/configuration-state.md
> +| coerce_c_locale            | 如果等于 2，则强制使用 C 语言环境； 如果等于 1，则读取 `LC_CTYPE` 的设置来决定是否强制使用C语言环境。 |
```suggestion
| coerce_c_locale            | 如果等于 2，则强制使用 C 语言环境； 如果等于 1，则读取 `LC_CTYPE` 的设置来决定是否强制使用 C 语言环境。 |

```

2022-06-13 03:23 UTC, xiaochen7 commented on configuration-and-input/configuration-state.md
> +1. `config->verbose` 的默认值是-1，硬编码在源码中；
```suggestion
1. `config->verbose` 的默认值是 -1，硬编码在源码中；

```
中文和数字之间建议加空格，参考issue里翻译规范。
建议其他地方再自查一下

2022-06-13 03:23 UTC, xiaochen7 commented on configuration-and-input/configuration-state.md
> +3. 如果环境变量不存在，将会保留默认值-1；
```suggestion
3. 如果环境变量不存在，将会保留默认值 -1；

```

2022-06-13 03:23 UTC, xiaochen7 commented on configuration-and-input/building-a-module-from-input.md
> +命令行中通过 `-c` 参数传入的内容会被传递给Modules/main.c 文件中 [pymain_run_command()](https://github.com/python/cpython/blob/v3.9.0b1/Modules/main.c#L226) 函数的 `wchar_t*` 类型的参数。
```suggestion
命令行中通过 `-c` 参数传入的内容会被传递给 Modules/main.c 文件中 [pymain_run_command()](https://github.com/python/cpython/blob/v3.9.0b1/Modules/main.c#L226) 函数的 `wchar_t*` 类型的参数。

```

2022-06-13 03:23 UTC, xiaochen7 commented on configuration-and-input/building-a-module-from-input.md
> +`wchar_t* ` 类型通常被用作低级存储类型，以便跨 CPython 的 Unicode 数据因为这种类型的大小可以存储UTF8字符。
> 以便跨 CPython 的 Unicode 数据因为这种类型的大小可以存储UTF8字符

这里读起来感觉有点别扭

2022-06-13 03:23 UTC, xiaochen7 commented on configuration-and-input/building-a-module-from-input.md
> +Python 模块是用于将解析后的代码交给编译器的数据结构。Python 模块的 C 数据结构名为 `mod_ty`，在Include/Python-ast.h 文件中定义
```suggestion
Python 模块是用于将解析后的代码交给编译器的数据结构。Python 模块的 C 数据结构名为 `mod_ty`，在 Include/Python-ast.h 文件中定义

```

2022-06-13 03:23 UTC, xiaochen7 commented on configuration-and-input/building-a-module-from-input.md
> +如果用户为python可执行程序传递了一个 `.pyc` 文件，那么 CPython 不会将文件作为纯文本文件加载并解析它，而是假定 `.pyc` 文件包含一个写入磁盘的 `code object`。
```suggestion
如果用户为 python 可执行程序传递了一个 `.pyc` 文件，那么 CPython 不会将文件作为纯文本文件加载并解析它，而是假定 `.pyc` 文件包含一个写入磁盘的 `code object`。

```

2022-06-13 09:31 UTC, lvluling commented on configuration-and-input/configuration-state.md
> +上述的两个数据结构都在 Include/cpython/initconfig.h 文件中定义。
原文用的是both，感觉是有点怪，先把“两个”去掉了

2022-06-13 09:31 UTC, lvluling commented on configuration-and-input/configuration-state.md
> +| configure_locale           | 将 `LC_CTYPE` 语言环境设置为用户首选语言环境。如果等于0，则将 `coerce_c_locale` 和 `coerce_c_locale_warn` 设置为0 |
done

2022-06-13 09:32 UTC, lvluling commented on configuration-and-input/building-a-module-from-input.md
> +命令行中通过 `-c` 参数传入的内容会被传递给Modules/main.c 文件中 [pymain_run_command()](https://github.com/python/cpython/blob/v3.9.0b1/Modules/main.c#L226) 函数的 `wchar_t*` 类型的参数。
done

2022-06-13 09:33 UTC, lvluling commented on configuration-and-input/configuration-state.md
> +3. 如果环境变量不存在，将会保留默认值-1；
done

2022-06-13 09:33 UTC, lvluling commented on configuration-and-input/building-a-module-from-input.md
> +`wchar_t* ` 类型通常被用作低级存储类型，以便跨 CPython 的 Unicode 数据因为这种类型的大小可以存储UTF8字符。
修改了一下：`wchar_t* ` 类型通常作为 CPython 中 Unicode 数据的低级存储类型，因为这种类型的大小可以存储 UTF8 字符。

2022-06-13 09:33 UTC, lvluling commented on configuration-and-input/building-a-module-from-input.md
> +Python 模块是用于将解析后的代码交给编译器的数据结构。Python 模块的 C 数据结构名为 `mod_ty`，在Include/Python-ast.h 文件中定义
done

2022-06-17 14:18 UTC, merged