Init translate of conduct.
shihai1991/CPython-Internals pull request #4
Opened 2022-03-24 16:22 UTC by shihai1991

2022-03-25 02:38 UTC, CharlieZhao95 requested changes
Some suggestions here.

2022-03-25 02:38 UTC, CharlieZhao95 commented on translate-of-conduct.md
> +
```suggestion
文章使用1级标题开头，内部小节标题级数逐级递减。

```

2022-03-25 02:38 UTC, CharlieZhao95 commented on translate-of-conduct.md
> +
```suggestion
三线表统一使用Markdown的内置表格功能，表格内数据字体不作要求。

```

2022-03-27 16:18 UTC, shihai1991 commented on translate-of-conduct.md
> +
这个交给你来扩写了。我自己还没遇到：）

2022-03-27 16:34 UTC, shihai1991 commented on translate-of-conduct.md
> +
第二行我接收了，其他后面遇到了再补充。6,7放到逗号那里就加了个链接应该够用吧。

2022-03-27 16:36 UTC, lijunchen commented
还有什么情况下可以添加译者注，以及以什么样的形式添加

2022-03-27 16:40 UTC, shihai1991 commented
> 还有什么情况下可以添加译者注，以及以什么样的形式添加

sorry。没有get到的问题。你说什么时候可以刷新这个规范？

2022-03-27 16:43 UTC, shihai1991 commented
> > 还有什么情况下可以添加译者注，以及以什么样的形式添加
> 
> 你说什么时候可以添加译者说明？这个后面遇到了我们再好好讨论讨论。暂时没想过这个问题:(

或者你有想法的话可以直接提issue和PR，我们可以在issue里面展开讨论：）

2022-03-28 02:15 UTC, merged